insert into locations (building_number, name) values ('0758','159 South Newton St');
insert into locations (building_number, name) values ('0757','259 Wadell St');
insert into locations (building_number, name) values ('2029','529 Baxter St');
insert into locations (building_number, name) values ('1060','Aderhold');
insert into locations (building_number, name) values ('0631','Administration Building');
insert into locations (building_number, name) values ('2426','Agronomy Seed Lab');
insert into locations (building_number, name) values ('2408','Agronomy Soil Building');
insert into locations (building_number, name) values ('2218','Alpha Chi Omega Sorority');
insert into locations (building_number, name) values ('2232','Alpha Epsilon Pi Fraternity');
insert into locations (building_number, name) values ('2255','Alpha Psi Vet. Fraternity');
insert into locations (building_number, name) values ('1077','Animal Health Research Center');
insert into locations (building_number, name) values ('2119','Automotive Services');
insert into locations (building_number, name) values ('2119','Auxiliary Services');
insert into locations (building_number, name) values ('0050','Baldwin Hall');
insert into locations (building_number, name) values ('1021','Barrow Hall');
insert into locations (building_number, name) values ('1686','Baseball Maintenance & Storage');
insert into locations (building_number, name) values ('1000','Biological Sciences Building');
insert into locations (building_number, name) values ('0032','Bishop House');
insert into locations (building_number, name) values ('2216','Boggs Hall');
insert into locations (building_number, name) values ('2210','Bolton Dining Commons ');
insert into locations (building_number, name) values ('1023','Boyd Graduate Research Center');
insert into locations (building_number, name) values ('0055','Brooks Hall');
insert into locations (building_number, name) values ('2213','Brumby Hall');
insert into locations (building_number, name) values ('0110','Business Services');
insert into locations (building_number, name) values ('0121','Business Services Annex');
insert into locations (building_number, name) values ('1671','Butts-Mehre Building');
insert into locations (building_number, name) values ('2438','CAGTECH');
insert into locations (building_number, name) values ('0046','Caldwell Hall');
insert into locations (building_number, name) values ('2118','Campus Mail/Environmental Safety');
insert into locations (building_number, name) values ('1637','Campus Transit Facility');
insert into locations (building_number, name) values ('0031','Candler Hall');
insert into locations (building_number, name) values ('1110','Carlton Street Deck');
insert into locations (building_number, name) values ('2419','CCRC');
insert into locations (building_number, name) values ('1630','Cedar Street Art Building');
insert into locations (building_number, name) values ('2127','Center for Applied Isotope Study');
insert into locations (building_number, name) values ('0178','Central Campus Mech. Building');
insert into locations (building_number, name) values ('2122','Central Food Storage');
insert into locations (building_number, name) values ('1620','Central Heating Plant 1');
insert into locations (building_number, name) values ('1618','Central Heating Plant 2');
insert into locations (building_number, name) values ('0103','Central Office Supply');
insert into locations (building_number, name) values ('0022','Chapel');
insert into locations (building_number, name) values ('1001','Chemistry');
insert into locations (building_number, name) values ('1004','Chemistry Annex');
insert into locations (building_number, name) values ('2200','Chi Phi Fraternity');
insert into locations (building_number, name) values ('0101','Chicopee Main Building No.1');
insert into locations (building_number, name) values ('1652','Child Development Laboratory');
insert into locations (building_number, name) values ('2215','Church Hall');
insert into locations (building_number, name) values ('0290','Clark Howell Hall');
insert into locations (building_number, name) values ('1656','Cobb House');
insert into locations (building_number, name) values ('1687','Coliseum Training Facility');
insert into locations (building_number, name) values ('1070','College of Veterinary Medicine 1');
insert into locations (building_number, name) values ('1011','Conner Hall');
insert into locations (building_number, name) values ('1248','Consumer Research Center');
insert into locations (building_number, name) values ('1043','Coop. Ext. Serv. - Hoke Smith');
insert into locations (building_number, name) values ('2627','Creative Problem Solving Lab ');
insert into locations (building_number, name) values ('2211','Creswell Hall');
insert into locations (building_number, name) values ('1057','Davison Life Sciences Complex ');
insert into locations (building_number, name) values ('1010','Dawson Hall    ');
insert into locations (building_number, name) values ('0045','Dean Rusk Hall');
insert into locations (building_number, name) values ('2219','Delta Phi Epsilon Sorority');
insert into locations (building_number, name) values ('0021','Demosthenian Hall');
insert into locations (building_number, name) values ('0044','Denmark Hall');
insert into locations (building_number, name) values ('1090','Driftmier Engineering Center');
insert into locations (building_number, name) values ('1698','East Campus Deck');
insert into locations (building_number, name) values ('1512','ECV 1512');
insert into locations (building_number, name) values ('1515','ECV McWhorter Hall');
insert into locations (building_number, name) values ('1513','ECV Rooker Hall');
insert into locations (building_number, name) values ('1514','ECV Vandiver Hall');
insert into locations (building_number, name) values ('1510','East Village Deck');
insert into locations (building_number, name) values ('1033','Ecology');
insert into locations (building_number, name) values ('1632','Electronics Shop');
insert into locations (building_number, name) values ('2425','Entomology Greenhouse/Headhouse');
insert into locations (building_number, name) values ('0766','Environmental Design Studios');
insert into locations (building_number, name) values ('1050','Environmental Health Sciences');
insert into locations (building_number, name) values ('2238','Family Housing Office');
insert into locations (building_number, name) values ('2221','Family Housing A ');
insert into locations (building_number, name) values ('2222','Family Housing B');
insert into locations (building_number, name) values ('2223','Family Housing C');
insert into locations (building_number, name) values ('2224','Family Housing D');
insert into locations (building_number, name) values ('2225','Family Housing E');
insert into locations (building_number, name) values ('2226','Family Housing F');
insert into locations (building_number, name) values ('2227','Family Housing G');
insert into locations (building_number, name) values ('2228','Family Housing H');
insert into locations (building_number, name) values ('2229','Family Housing J');
insert into locations (building_number, name) values ('2230','Family Housing K');
insert into locations (building_number, name) values ('2231','Family Housing L');
insert into locations (building_number, name) values ('2240','Family Housing M');
insert into locations (building_number, name) values ('2241','Family Housing N');
insert into locations (building_number, name) values ('2242','Family Housing P');
insert into locations (building_number, name) values ('2243','Family Housing Q');
insert into locations (building_number, name) values ('2244','Family Housing R');
insert into locations (building_number, name) values ('2245','Family Housing S');
insert into locations (building_number, name) values ('2260','Family Housing T');
insert into locations (building_number, name) values ('2261','Family Housing U');
insert into locations (building_number, name) values ('2262','Family Housing V');
insert into locations (building_number, name) values ('1246','Family Science Center 1');
insert into locations (building_number, name) values ('1249','Family Science Center 2');
insert into locations (building_number, name) values ('0060','Fine Arts Building');
insert into locations (building_number, name) values ('1685','Foley Baseball Stadium');
insert into locations (building_number, name) values ('1022','Food Processing Lab');
insert into locations (building_number, name) values ('1020','Food Science Building');
insert into locations (building_number, name) values ('1040','Forestry Resources 1');
insert into locations (building_number, name) values ('1140','Forestry Resources 2');
insert into locations (building_number, name) values ('1044','Forestry Resources 3');
insert into locations (building_number, name) values ('1046','Forestry Resources 4');
insert into locations (building_number, name) values ('2835','Four Towers');
insert into locations (building_number, name) values ('0005','Franklin House');
insert into locations (building_number, name) values ('0650','Garden Club of Georgia');
insert into locations (building_number, name) values ('1002','Geography and Geology');
insert into locations (building_number, name) values ('0090','Geology Hydrothermal Lab');
insert into locations (building_number, name) values ('1640','Georgia Center for Cont Ed');
insert into locations (building_number, name) values ('1693','Georgia Museum of Art ');
insert into locations (building_number, name) values ('0640','Gilbert Hall');
insert into locations (building_number, name) values ('0756','Government Relations');
insert into locations (building_number, name) values ('1031','Hardman Hall');
insert into locations (building_number, name) values ('2410','Headhouse Horticulture');
insert into locations (building_number, name) values ('2411','Headhouse Plants Agronomy ');
insert into locations (building_number, name) values ('2622','Henry Feild Tennis Stadium ');
insert into locations (building_number, name) values ('2214','Hill Hall');
insert into locations (building_number, name) values ('0043','Hirsch Hall');
insert into locations (building_number, name) values ('0019','Hodgson Oil Building');
insert into locations (building_number, name) values ('1042','Hoke Smith Annex');
insert into locations (building_number, name) values ('0120','Holmes/Hunter Academic Building');
insert into locations (building_number, name) values ('1340','Horticulture Greenhouse');
insert into locations (building_number, name) values ('1340','Horticulture Greenhouse');
insert into locations (building_number, name) values ('2423','Horticulture Greenhouse 1');
insert into locations (building_number, name) values ('1247','Housing Research Center');
insert into locations (building_number, name) values ('1691','Hugh Hodgson School of Music ');
insert into locations (building_number, name) values ('0082','Hull Street Deck');
insert into locations (building_number, name) values ('0620','Human Resources');
insert into locations (building_number, name) values ('0066','Instructional Plaza');
insert into locations (building_number, name) values ('0033','Interim Medical Partnership Building');
insert into locations (building_number, name) values ('0767','Interior Design Studios');
insert into locations (building_number, name) values ('2634','Intramural Field Equipment Shed');
insert into locations (building_number, name) values ('2972','Intramural Fields Deck');
insert into locations (building_number, name) values ('2632','Intramural Fields Restrooms');
insert into locations (building_number, name) values ('2970','Intramural Tennis Pavilion ');
insert into locations (building_number, name) values ('1675','J.W. Fanning Building');
insert into locations (building_number, name) values ('1511','Joe Frank Harris Commons');
insert into locations (building_number, name) values ('0250','Joseph E. Brown Hall');
insert into locations (building_number, name) values ('0062','Journalism Building');
insert into locations (building_number, name) values ('1668','Judges Tower');
insert into locations (building_number, name) values ('2233','Kappa Sigma Fraternity');
insert into locations (building_number, name) values ('2440','Lake Herrick Pavilion');
insert into locations (building_number, name) values ('1694','Lamar Dodd School of Art ');
insert into locations (building_number, name) values ('2414','Lath Greenhouse 3 Botony ');
insert into locations (building_number, name) values ('1354','LathGreenhouse 1');
insert into locations (building_number, name) values ('0043','Law Library Annex');
insert into locations (building_number, name) values ('0043','Law School Addition');
insert into locations (building_number, name) values ('0053','LeConte Hall');
insert into locations (building_number, name) values ('2604','Legion Pool ');
insert into locations (building_number, name) values ('1058','Life Sciences Fermentation Lab');
insert into locations (building_number, name) values ('2623','Lindsey Hopkins Indoor Tennis Stadium ');
insert into locations (building_number, name) values ('2208','Lipscomb Hall');
insert into locations (building_number, name) values ('1012','Lumpkin House');
insert into locations (building_number, name) values ('0632','Lustrat House');
insert into locations (building_number, name) values ('0054','Main Library');
insert into locations (building_number, name) values ('1030','Marine Science / Dance');
insert into locations (building_number, name) values ('1221','Mary Lyndon Hall');
insert into locations (building_number, name) values ('0024','Meigs Hall');
insert into locations (building_number, name) values ('2209','Mell Hall');
insert into locations (building_number, name) values ('0670','Memorial Hall');
insert into locations (building_number, name) values ('1679','Mens Tennis Clubhouse');
insert into locations (building_number, name) values ('0061','Military Building Army ROTC');
insert into locations (building_number, name) values ('0271','Milledge Hall');
insert into locations (building_number, name) values ('1061','Miller Plant Science');
insert into locations (building_number, name) values ('0025','Moore College');
insert into locations (building_number, name) values ('2204','Morris Hall');
insert into locations (building_number, name) values ('1222','Myers Hall');
insert into locations (building_number, name) values ('0030','New College');
insert into locations (building_number, name) values ('0122','North Campus Deck');
insert into locations (building_number, name) values ('0113','Office of University Architects');
insert into locations (building_number, name) values ('2257','Oglethorpe Dining Commons');
insert into locations (building_number, name) values ('2217','Oglethorpe House');
insert into locations (building_number, name) values ('0130','Old College');
insert into locations (building_number, name) values ('2256','Omega Tau Sigma Fraternity');
insert into locations (building_number, name) values ('0056','Park Hall');
insert into locations (building_number, name) values ('1111','Paul D. Coverdell Center');
insert into locations (building_number, name) values ('0270','Payne Hall');
insert into locations (building_number, name) values ('0042','Peabody Hall');
insert into locations (building_number, name) values ('1692','Performing Arts ');
insert into locations (building_number, name) values ('1699','Performing Arts Complex Deck ');
insert into locations (building_number, name) values ('2293','Phi Delta Theta Fraternity ');
insert into locations (building_number, name) values ('0020','Phi Kappa Hall');
insert into locations (building_number, name) values ('1642','Physical Plant Grounds');
insert into locations (building_number, name) values ('1641','Physical Plant Utility');
insert into locations (building_number, name) values ('1003','Physics Building');
insert into locations (building_number, name) values ('2294','Pi Kappa Alpha Fraternity');
insert into locations (building_number, name) values ('1013','Poultry Science');
insert into locations (building_number, name) values ('2130','Printing Department');
insert into locations (building_number, name) values ('0768','Printing Studios');
insert into locations (building_number, name) values ('0064','Psychology Building');
insert into locations (building_number, name) values ('2634','Public Service & Outreach');
insert into locations (building_number, name) values ('1041','R. C. Wilson Pharmacy');
insert into locations (building_number, name) values ('1690','Ramsey Center ');
insert into locations (building_number, name) values ('2614','Recording for the Blind ');
insert into locations (building_number, name) values ('0280','Reed Hall');
insert into locations (building_number, name) values ('2417','Rhizotron Building ');
insert into locations (building_number, name) values ('1501','Rhodes Animal Science Center - A');
insert into locations (building_number, name) values ('1502','Rhodes Animal Science Center - B');
insert into locations (building_number, name) values ('1503','Rhodes Animal Science Center - C');
insert into locations (building_number, name) values ('2125','Riverbend Research Lab North');
insert into locations (building_number, name) values ('2418','Riverbend Research Lab South ');
insert into locations (building_number, name) values ('2124','Riverbend Solvent Storage Bldg');
insert into locations (building_number, name) values ('2212','Russell Hall');
insert into locations (building_number, name) values ('1210','Rutherford Hall');
insert into locations (building_number, name) values ('0058','Sanford Hall');
insert into locations (building_number, name) values ('0678','Sanford Stadium');
insert into locations (building_number, name) values ('1621','Science Library');
insert into locations (building_number, name) values ('2680','Sculpture & Ceramics Studio');
insert into locations (building_number, name) values ('0124','Sculpture Canopy');
insert into locations (building_number, name) values ('2373','Shop Building');
insert into locations (building_number, name) values ('2205','Sigma Chi Fraternity');
insert into locations (building_number, name) values ('2220','Sigma Delta Tau Sorority');
insert into locations (building_number, name) values ('2291','Sigma Nu Fraternity');
insert into locations (building_number, name) values ('1643','Snelling Dinning Hall');
insert into locations (building_number, name) values ('2409','Soil Building 2');
insert into locations (building_number, name) values ('2437','Soil Chemical & Equipment Bldg');
insert into locations (building_number, name) values ('2413','Soil Storage Building');
insert into locations (building_number, name) values ('1094','Soil Tillage Laboratory');
insert into locations (building_number, name) values ('1220','Soule Hall');
insert into locations (building_number, name) values ('1617','South Campus Chiller Building');
insert into locations (building_number, name) values ('1139','South Campus Deck');
insert into locations (building_number, name) values ('1010','Speirs Hall');
insert into locations (building_number, name) values ('2685','Staff Training & Development ');
insert into locations (building_number, name) values ('1130','Statistics & Computer Services');
insert into locations (building_number, name) values ('1654','Stegeman Coliseum');
insert into locations (building_number, name) values ('2362','Storage Barn ');
insert into locations (building_number, name) values ('1665','Storage Shed');
insert into locations (building_number, name) values ('1673','Student Athlete Academic Center');
insert into locations (building_number, name) values ('0123','Tanner Building');
insert into locations (building_number, name) values ('0669','Tate Parking Deck');
insert into locations (building_number, name) values ('0672','Tate Student Center');
insert into locations (building_number, name) values ('2292','Tau Epsilon Phi Fraternity');
insert into locations (building_number, name) values ('1670','Tennis Hall of Fame');
insert into locations (building_number, name) values ('0023','Terrell Hall');
insert into locations (building_number, name) values ('2606','Thomas Street Art Studio ');
insert into locations (building_number, name) values ('2691','Thomas Street Sculpture ');
insert into locations (building_number, name) values ('2600','Thomas Street South ');
insert into locations (building_number, name) values ('1657','Treanor House');
insert into locations (building_number, name) values ('1250','Tucker Hall');
insert into locations (building_number, name) values ('1701','UGA Health Center');
insert into locations (building_number, name) values ('2636','UGA Real Estate Foundation ');
insert into locations (building_number, name) values ('0671','University Bookstore');
insert into locations (building_number, name) values ('1634','Vehicle Transporation & Maintenance');
insert into locations (building_number, name) values ('1084','Vet Med BioResources');
insert into locations (building_number, name) values ('1079','Vet Med Diagnostic Lab');
insert into locations (building_number, name) values ('1064','Vet. Med. Locomotive Diag. Ctr.');
insert into locations (building_number, name) values ('1066','Vet. Medicine 10');
insert into locations (building_number, name) values ('1067','Vet. Medicine 11');
insert into locations (building_number, name) values ('1068','Vet. Medicine 12');
insert into locations (building_number, name) values ('1072','Vet. Medicine 2');
insert into locations (building_number, name) values ('1680','Vet. Medicine 5A');
insert into locations (building_number, name) values ('1682','Vet. Medicine 5C');
insert into locations (building_number, name) values ('1683','Vet. Medicine 5D');
insert into locations (building_number, name) values ('1073','Vet. Medicine 6');
insert into locations (building_number, name) values ('1065','Vet. Medicine 9');
insert into locations (building_number, name) values ('2371','Vet. Medicine Barn');
insert into locations (building_number, name) values ('2370','Vet. Medicine Block Building');
insert into locations (building_number, name) values ('2383','Vet. Medicine Fish Barn ');
insert into locations (building_number, name) values ('2352','Vet. Medicine Pole Barn');
insert into locations (building_number, name) values ('2368','Vet. Medicine Shop ');
insert into locations (building_number, name) values ('2369','Vet. Medicine Storage ');
insert into locations (building_number, name) values ('0040','Visual Arts');
insert into locations (building_number, name) values ('0041','Waddel Hall');
insert into locations (building_number, name) values ('2136','West Campus Deck');
insert into locations (building_number, name) values ('1082','Wildlife Health');
insert into locations (building_number, name) values ('1678','Womens Tennis Clubhouse');
insert into locations (building_number, name) values ('0751','Wray-Nicholson House');
insert into locations (building_number, name) values ('0754','Wray-Nicholson Prop 150');
insert into locations (building_number, name) values ('0755','Wray-Nicholson Prop 154');
insert into locations (building_number, name) values ('0753','Wray-Nicholson Prop 290');
insert into locations (building_number, name) values ('0752','Wray-Nicholson Props 240');
insert into locations (building_number, name) values ('0081','Zell B. Miller Learning Center');
